#### Bibliotecas

- Pandas : Ler o dataset final
- pyarrow : Ler o parquet da Camada Ouro
- psycopg2 : Conectar Python ao PostgreSQL
- SQLAlchemy : Inserir o dataset no banco

In [1]:
!pip install pandas pyarrow psycopg2-binary sqlalchemy

Requirement already satisfied: pandas in C:\Users\alvar\anaconda3\Lib\site-packages (2.3.2)
Requirement already satisfied: pyarrow in C:\Users\alvar\anaconda3\Lib\site-packages (21.0.0)
Requirement already satisfied: psycopg2-binary in C:\Users\alvar\anaconda3\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\alvar\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\alvar\anaconda3\Lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\alvar\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\alvar\anaconda3\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\alvar\anaconda3\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: greenlet>=1 in C:\Users\alvar\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\alvar\anaconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\alvar\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import os
from sqlalchemy import create_engine

In [3]:
# Le a Camada Ouro gerada pelo Transform.ipynb
PASTA_DADOS = os.path.join("..", "dados")
PASTA_GOLD = os.path.join(PASTA_DADOS, "gold")

df_dataset = pd.read_parquet(os.path.join(PASTA_GOLD, "dataset_energia_solar.parquet"))
display(df_dataset)

,ranking_nacional,municipio,uf,regiao,renda_per_capita,Qtd_Conexoes_Total,Potencia_Instalada_KW_Total,populacao_residente,area_unidade_territorial_km2,densidade_demografica,Estado,ghi_media_kwh_m2_dia
0,65,Fernando de Noronha,PE,Nordeste,2566.14,25,386.07,3167,18.609,170.19,Pernambuco,NaN
1,81,Eusébio,CE,Nordeste,2512.70,5370,42413.98,74170,78.818,941.03,Ceará,5.730
2,152,Recife,PE,Nordeste,2284.77,11851,82064.10,1488920,218.843,6803.60,Pernambuco,5.462
3,287,Aracaju,SE,Nordeste,2087.74,8086,62395.61,602757,182.163,3308.89,Sergipe,5.496
4,321,Natal,RN,Nordeste,2049.37,18634,124543.84,751300,167.401,4488.03,Rio Grande do Norte,5.674
...,...,...,...,...,...,...,...,...,...,...,...,...
1789,5563,Humberto de Campos,MA,Nordeste,415.69,39,750.30,25680,1714.625,14.98,Maranhão,5.253
1790,5564,Primeira Cruz,MA,Nordeste,413.00,22,217.59,13614,1337.161,10.18,Maranhão,5.304
1791,5566,Cachoeira Grande,MA,Nordeste,389.45,5,43.00,9732,707.236,13.76,Maranhão,4.986
1792,5567,Belágua,MA,Nordeste,388.46,6,77.95,8460,569.606,14.85,Maranhão,5.337
1793,5568,Manari,PE,Nordeste,359.10,56,476.89,23763,344.685,68.94,Pernambuco,5.578

In [4]:
# Conexao com o PostgreSQL
engine = create_engine(
    "postgresql://admin:admin123@localhost:5435/energia_solar"
)

with engine.connect() as conn:
    print("Conexão PostgreSQL realizada com sucesso")

Conexão PostgreSQL realizada com sucesso

In [5]:
# Camada Ouro - dataset final no banco
df_dataset.to_sql(
    name="dataset_energia_solar",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset inserido com sucesso!")
print(f"   Tabela: dataset_energia_solar")
print(f"   Linhas: {len(df_dataset)}")
print(f"   Colunas: {list(df_dataset.columns)}")

Dataset inserido com sucesso!
   Tabela: dataset_energia_solar
   Linhas: 1794
   Colunas: ['ranking_nacional', 'municipio', 'uf', 'regiao', 'renda_per_capita', 'Qtd_Conexoes_Total', 'Potencia_Instalada_KW_Total', 'populacao_residente', 'area_unidade_territorial_km2', 'densidade_demografica', 'Estado', 'ghi_media_kwh_m2_dia']

In [6]:
df_verificacao = pd.read_sql(
    "SELECT * FROM dataset_energia_solar",
    engine
)

display(df_verificacao)

,ranking_nacional,municipio,uf,regiao,renda_per_capita,Qtd_Conexoes_Total,Potencia_Instalada_KW_Total,populacao_residente,area_unidade_territorial_km2,densidade_demografica,Estado,ghi_media_kwh_m2_dia
0,65,Fernando de Noronha,PE,Nordeste,2566.14,25,386.07,3167,18.609,170.19,Pernambuco,NaN
1,81,Eusébio,CE,Nordeste,2512.70,5370,42413.98,74170,78.818,941.03,Ceará,5.730
2,152,Recife,PE,Nordeste,2284.77,11851,82064.10,1488920,218.843,6803.60,Pernambuco,5.462
3,287,Aracaju,SE,Nordeste,2087.74,8086,62395.61,602757,182.163,3308.89,Sergipe,5.496
4,321,Natal,RN,Nordeste,2049.37,18634,124543.84,751300,167.401,4488.03,Rio Grande do Norte,5.674
...,...,...,...,...,...,...,...,...,...,...,...,...
1789,5563,Humberto de Campos,MA,Nordeste,415.69,39,750.30,25680,1714.625,14.98,Maranhão,5.253
1790,5564,Primeira Cruz,MA,Nordeste,413.00,22,217.59,13614,1337.161,10.18,Maranhão,5.304
1791,5566,Cachoeira Grande,MA,Nordeste,389.45,5,43.00,9732,707.236,13.76,Maranhão,4.986
1792,5567,Belágua,MA,Nordeste,388.46,6,77.95,8460,569.606,14.85,Maranhão,5.337
1793,5568,Manari,PE,Nordeste,359.10,56,476.89,23763,344.685,68.94,Pernambuco,5.578